export declare const tipoImovelEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["casa", "apartamento", "terreno", "comercial", "cobertura"]>;
export declare const statusImovelEnum: import("node_modules/drizzle-orm/pg-core").PgEnum<["disponivel", "reservado", "vendido", "alugado"]>;
export declare const imoveis: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "imoveis";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "imoveis";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        titulo: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "titulo";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        descricao: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "descricao";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        tipo: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tipo";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "casa" | "apartamento" | "terreno" | "comercial" | "cobertura";
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["casa", "apartamento", "terreno", "comercial", "cobertura"];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<"casa" | "apartamento" | "terreno" | "comercial" | "cobertura">;
        }, {}, {}>;
        status: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "status";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgEnumColumn";
            data: "disponivel" | "reservado" | "vendido" | "alugado";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: ["disponivel", "reservado", "vendido", "alugado"];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<"disponivel" | "reservado" | "vendido" | "alugado">;
        }, {}, {}>;
        precoVenda: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "preco_venda";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        precoAluguel: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "preco_aluguel";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        valorIptu: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "valor_iptu";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        valorCondominio: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "valor_condominio";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        areaPrivativa: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "area_privativa";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        areaTotal: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "area_total";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        quartos: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "quartos";
            tableName: "imoveis";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        suites: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "suites";
            tableName: "imoveis";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        banheiros: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "banheiros";
            tableName: "imoveis";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        vagasGaragem: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "vagas_garagem";
            tableName: "imoveis";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        endereco: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "endereco";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        bairro: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "bairro";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        cidade: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "cidade";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        estado: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "estado";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        lat: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "lat";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        lng: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "lng";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        tourVirtualUrl: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tour_virtual_url";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        videoApresentacaoUrl: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "video_url";
            tableName: "imoveis";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        createdAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "created_at";
            tableName: "imoveis";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<Date>;
        }, {}, {}>;
        updatedAt: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "updated_at";
            tableName: "imoveis";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<Date>;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const infraestrutura: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "infraestrutura";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "infraestrutura";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        imovelId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "imovel_id";
            tableName: "infraestrutura";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        temAguaQuente: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tem_agua_quente";
            tableName: "infraestrutura";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<boolean>;
        }, {}, {}>;
        temEsperaSplit: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tem_espera_split";
            tableName: "infraestrutura";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<boolean>;
        }, {}, {}>;
        temGasCentral: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tem_gas_central";
            tableName: "infraestrutura";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<boolean>;
        }, {}, {}>;
        temChurrasqueira: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tem_churrasqueira";
            tableName: "infraestrutura";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<boolean>;
        }, {}, {}>;
        temLareira: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tem_lareira";
            tableName: "infraestrutura";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<boolean>;
        }, {}, {}>;
        temPiscina: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tem_piscina";
            tableName: "infraestrutura";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<boolean>;
        }, {}, {}>;
        permitePets: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "permite_pets";
            tableName: "infraestrutura";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<boolean>;
        }, {}, {}>;
        mobiliado: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "mobiliado";
            tableName: "infraestrutura";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<boolean>;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const inventario: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "inventario";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "inventario";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        imovelId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "imovel_id";
            tableName: "inventario";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        item: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "item";
            tableName: "inventario";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        quantidade: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "quantidade";
            tableName: "inventario";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        estadoConservacao: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "estado";
            tableName: "inventario";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const instrucoesChegada: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "instrucoes_chegada";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "instrucoes_chegada";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        imovelId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "imovel_id";
            tableName: "instrucoes_chegada";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        ordem: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "ordem";
            tableName: "instrucoes_chegada";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        titulo: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "titulo";
            tableName: "instrucoes_chegada";
            dataType: "string";
            columnType: "PgVarchar";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        descricao: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "descricao";
            tableName: "instrucoes_chegada";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        fotoUrl: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "foto_url";
            tableName: "instrucoes_chegada";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        latAlvo: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "lat_alvo";
            tableName: "instrucoes_chegada";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        lngAlvo: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "lng_alvo";
            tableName: "instrucoes_chegada";
            dataType: "string";
            columnType: "PgNumeric";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const midiaImovel: import("node_modules/drizzle-orm/pg-core").PgTableWithColumns<{
    name: "midia_imovel";
    schema: undefined;
    columns: {
        id: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "midia_imovel";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        imovelId: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "imovel_id";
            tableName: "midia_imovel";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
        url: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "url";
            tableName: "midia_imovel";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        tipo: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "tipo";
            tableName: "midia_imovel";
            dataType: "string";
            columnType: "PgVarchar";
            data: "foto" | "foto360" | "planta";
            driverParam: string;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<string>;
        }, {}, {}>;
        ordem: import("node_modules/drizzle-orm/pg-core").PgColumn<{
            name: "ordem";
            tableName: "midia_imovel";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            generated: import("node_modules/drizzle-orm").GeneratedColumnConfig<number>;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const imoveisRelations: import("node_modules/drizzle-orm").Relations<"imoveis", {
    infraestrutura: import("node_modules/drizzle-orm").One<"infraestrutura", true>;
    inventario: import("node_modules/drizzle-orm").Many<"inventario">;
    instrucoes: import("node_modules/drizzle-orm").Many<"instrucoes_chegada">;
    midias: import("node_modules/drizzle-orm").Many<"midia_imovel">;
}>;
